# Generated by Django 4.2.2 on 2023-06-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='day_shift',
            field=models.DateField(auto_now_add=True),
        ),
    ]
