# Generated by Django 4.2.2 on 2023-06-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='number',
        ),
        migrations.AlterField(
            model_name='court',
            name='court_type',
            field=models.CharField(choices=[('1', 'Cemento'), ('2', 'Sintetico'), ('3', 'Parquet')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('1', 'Paypal')], max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='sex',
            field=models.CharField(choices=[('1', 'Female'), ('2', 'Male')], max_length=50),
        ),
        migrations.AlterField(
            model_name='shift',
            name='hour',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='shift',
            name='status',
            field=models.CharField(choices=[('1', 'Disponible'), ('2', 'Reservado')], default=1, max_length=50),
        ),
    ]
