# Generated by Django 4.2.2 on 2023-06-23 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0002_alter_shift_day_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='shift',
            name='day_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canchas.day'),
        ),
    ]
