# Generated by Django 4.2.2 on 2023-06-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0003_day_alter_shift_day_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='day_shift',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
