# Generated by Django 4.2.2 on 2023-06-27 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0005_alter_reservation_court_res_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='court_res',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canchas.court'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='sport_res',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canchas.sports'),
        ),
    ]
