# Generated by Django 4.2.2 on 2023-06-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0006_alter_reservation_court_res_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='rate_res',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
